"""Generate a Markdown smoke test report from StepCollector data."""
from __future__ import annotations

from datetime import datetime
from typing import List

from crisp.config import CRISPConfig
from crisp.workflow.collector import IterationData, StepCollector


PLAYER_NAMES = {0: "Alice", 1: "Bob"}


def _detail_iterations(total: int) -> List[int]:
    """Return which iterations to show in full detail.

    Shows first 3, last, and evenly-spaced milestones for longer runs.
    """
    iters = set(range(min(3, total)))
    if total > 3:
        iters.add(total - 1)
    # Add milestones every 5 iterations for runs > 10
    if total > 10:
        for i in range(4, total - 1, 5):
            iters.add(i)
    return sorted(iters)


def generate_report(collector: StepCollector, config: CRISPConfig) -> str:
    """Generate a Markdown report string from collected iteration data."""
    lines: List[str] = []

    model = config.training.model_name
    total = len(collector.iterations)
    batch_size = config.coach.batch_size
    rollouts_per = config.player.rollouts_per_problem

    lines.append("# CRISP Smoke Test Report")
    lines.append(f"**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"**Model**: {model}")
    lines.append(f"**Iterations**: {total} | **Problems/iter**: {batch_size} | **Rollouts/problem**: {rollouts_per}")
    lines.append("")

    # --- Summary table ---
    lines.append("## Summary")
    lines.append("")
    max_new_tokens = config.player.max_new_tokens
    lines.append("| Iter | Problems | Disc | Acc | Parsed% | Trunc% | Avg Tok | Max Tok | A Loss | B Loss | C Loss |")
    lines.append("|------|----------|------|-----|---------|--------|---------|---------|--------|--------|--------|")
    for data in collector.iterations:
        r = data.result
        cl = f"{r.coach_loss:.4f}" if r.coach_loss is not None else "N/A"
        # Token stats across all player rollouts
        all_rollouts = []
        for pid in data.rollouts:
            all_rollouts.extend(data.rollouts[pid])
        tok_lens = [len(ro.tokens) for ro in all_rollouts] if all_rollouts else [0]
        avg_tok = sum(tok_lens) / len(tok_lens)
        max_tok = max(tok_lens)
        parsed_count = sum(1 for ro in all_rollouts if ro.answer is not None)
        parsed_pct = parsed_count / len(all_rollouts) * 100 if all_rollouts else 0
        trunc_count = sum(
            1 for ro in all_rollouts
            if (len(ro.tokens) - getattr(ro, 'prompt_len', 0)) >= max_new_tokens
        )
        trunc_pct = trunc_count / len(all_rollouts) * 100 if all_rollouts else 0
        lines.append(
            f"| {data.iteration} | {r.num_problems} | {r.num_discussions} "
            f"| {r.player_accuracy:.3f} | {parsed_pct:.0f}% | {trunc_pct:.0f}% "
            f"| {avg_tok:.0f} | {max_tok} "
            f"| {r.alice_loss:.4f} | {r.bob_loss:.4f} | {cl} |"
        )
    lines.append("")

    # --- Detailed sections ---
    detail_iters = _detail_iterations(total)
    for data in collector.iterations:
        if data.iteration not in detail_iters:
            continue
        lines.append(f"## Iteration {data.iteration}")
        lines.append("")
        _write_problems_section(lines, data)
        _write_rollouts_section(lines, data)
        _write_unparsed_samples(lines, data)
        _write_discussion_section(lines, data)
        _write_coach_rewards_section(lines, data)
        lines.append(f"**Player Loss**: {data.player_loss:.4f}")
        if data.coach_loss is not None:
            lines.append(f"**Coach Loss**: {data.coach_loss:.4f}")
        lines.append("")
        lines.append("---")
        lines.append("")

    # --- Trend summary ---
    lines.append("## Trends")
    lines.append("")
    lines.append("| Iter | Acc | A Loss | B Loss | C Loss | Avg C Reward | Problems |")
    lines.append("|------|-----|--------|--------|--------|-------------|----------|")
    for d in collector.iterations:
        cl = f"{d.coach_loss:.4f}" if d.coach_loss is not None else "N/A"
        if d.coach_rewards:
            avg_cr = sum(d.coach_rewards) / len(d.coach_rewards)
            avg_cr_str = f"{avg_cr:+.3f}"
        else:
            avg_cr_str = "N/A"
        lines.append(
            f"| {d.iteration} | {d.result.player_accuracy:.3f} "
            f"| {d.result.alice_loss:.4f} | {d.result.bob_loss:.4f} | {cl} | {avg_cr_str} "
            f"| {d.result.num_problems} |"
        )
    lines.append("")

    return "\n".join(lines)


def _write_problems_section(lines: List[str], data: IterationData) -> None:
    lines.append("### Problems Generated by Coach")
    lines.append("")
    for i, prob in enumerate(data.problems):
        gt = prob.ground_truth
        text = prob.text[:200] + "..." if len(prob.text) > 200 else prob.text
        lines.append(f"**Problem {i + 1}**: \"{text}\"")
        lines.append(f"**Ground Truth**: `{gt}`")
        lines.append("")


def _write_rollouts_section(lines: List[str], data: IterationData) -> None:
    for prob_idx, prob in enumerate(data.problems):
        lines.append(f"### Player Rollouts - Problem {prob_idx + 1}")
        lines.append("")
        lines.append("| Player | # | Tokens | Answer | Correct | Reward |")
        lines.append("|--------|---|--------|--------|---------|--------|")

        for pid in [0, 1]:
            player_name = PLAYER_NAMES[pid]
            rollouts = [r for r in data.rollouts.get(pid, []) if r.problem_idx == prob_idx]
            for j, r in enumerate(rollouts):
                ans = r.answer if r.answer is not None else "-"
                correct_str = "Y" if r.correct else ("N" if r.correct is not None else "-")
                n_tok = len(r.tokens)
                lines.append(f"| {player_name} | {j + 1} | {n_tok} | {ans} | {correct_str} | {r.reward:.2f} |")
        lines.append("")


def _write_unparsed_samples(lines: List[str], data: IterationData, max_samples: int = 3) -> None:
    """Show the tail of a few unparsed rollouts so we can diagnose why parsing failed."""
    unparsed = []
    for pid in [0, 1]:
        for r in data.rollouts.get(pid, []):
            if r.answer is None:
                unparsed.append((PLAYER_NAMES[pid], r))
    if not unparsed:
        return

    lines.append("### Unparsed Rollout Samples (last 300 chars)")
    lines.append("")
    for player_name, r in unparsed[:max_samples]:
        n_tok = len(r.tokens)
        tail = r.text[-300:] if len(r.text) > 300 else r.text
        tail = tail.replace("\n", " ↵ ")
        lines.append(f"**{player_name}** p{r.problem_idx} ({n_tok} tok): `{tail}`")
        lines.append("")


def _write_discussion_section(lines: List[str], data: IterationData) -> None:
    discussed = set()
    for pid in data.discussion_results:
        for dr in data.discussion_results[pid]:
            discussed.add(dr.problem_idx)

    if not discussed:
        lines.append("### Discussion")
        lines.append("No discussions triggered (all problems had agreement).")
        lines.append("")
        return

    lines.append("### Discussion")
    lines.append("")

    for prob_idx in sorted(discussed):
        prob = data.problems[prob_idx] if prob_idx < len(data.problems) else None
        prob_text = prob.text[:100] if prob else "?"

        maj_a = data.majority_answers.get((0, prob_idx), "None")
        maj_b = data.majority_answers.get((1, prob_idx), "None")
        lines.append(f"**Problem {prob_idx + 1}** (\"{prob_text[:60]}...\")")
        lines.append(f"  Alice majority=`{maj_a}`, Bob majority=`{maj_b}` -> DISAGREE")
        lines.append("")

        for pid in [0, 1]:
            player_name = PLAYER_NAMES[pid]
            drs = [dr for dr in data.discussion_results.get(pid, []) if dr.problem_idx == prob_idx]
            for dr in drs:
                correct_str = "Y" if dr.correct else "N"
                lines.append(f"  **{player_name} post-discussion**:")
                eval_text = dr.evaluation_text[:150] if dr.evaluation_text else "(empty)"
                lines.append(f"  > Evaluation: {eval_text}")
                lines.append(f"  > Final Answer: `{dr.final_answer}` | Correct: {correct_str} | Reward: {dr.reward:.2f}")
                lines.append("")


def _write_coach_rewards_section(lines: List[str], data: IterationData) -> None:
    if data.coach_rewards is None:
        return

    lines.append("### Coach Rewards")
    lines.append("")
    lines.append("| Problem | Reward |")
    lines.append("|---------|--------|")
    for i, reward in enumerate(data.coach_rewards):
        lines.append(f"| {i + 1} | {reward:.4f} |")
    lines.append("")
